version: '3'
services:
  promtail:
    image:  grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - /mnt/mytmpfs:/var/log/suricata
    command: -config.file=/etc/promtail/promtail.yml
